---
title: 25x52.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: 25x52
description: An initiative to launch 25 projects in 52 weeks
avatar: https://pbs.twimg.com/profile_images/495652623005917184/ZhwRUMXo.png
footer-links:
  dribbble: 
  email: femmebot@gmail.com
  facebook: 
  flickr: 
  github: femmebot
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: femmebot
  stackoverflow: 
disqus: 
google_analytics: UA-51931-4
url: http://25x52.com
baseurl: ''
markdown: kramdown
highlighter: pygments
permalink: "/:title/"
version: v1.0.0
sass:
  sass_dir: _scss
  style: :expanded
gems:
- jemoji
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
