---
title: 25x52.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: 25x52
description: An initiative to launch 25 projects in 52 weeks
avatar: https://pbs.twimg.com/profile_images/495652623005917184/ZhwRUMXo.png
footer-links:
  dribbble: 
  email: femmebot@gmail.com
  facebook: 
  flickr: 
  github: femmebot
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: femmebot
  stackoverflow: 
disqus: 
google_analytics: UA-51931-4
url: http://25x52.com
baseurl: ''
# markdown: kramdown
# highlighter: rouge
permalink: "/:title/"
version: v1.0.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

sass:
  sass_dir: _scss
  style: :expanded
gems:
- jemoji
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
